// src/app/PlayHistoryList.tsx
import React, { useCallback, useState } from "react";
import { PlayHistory, Position, UserActionDetail } from "./Game.types";

interface HistoryListProps {
    playHistory: PlayHistory[] | null;
    onRetry: (seed: string, firstStep: Position) => void;
    onReplay: (seed: string, actions: UserActionDetail[]) => void;
}

const PlayHistoryList = React.memo(function HistoryList({ playHistory, onRetry, onReplay }: HistoryListProps) {
    const [expandedIndex, setExpandedIndex] = useState<number | null>(playHistory?.length ?? 0 > 0 ? 0 : null);

    const handleItemClick = useCallback((index: number) => {
        setExpandedIndex(expandedIndex === index ? null : index);
    }, [expandedIndex]);

    const handleRetry = useCallback((entry: PlayHistory) => {
        const firstStep = entry.actions.at(0)?.position;
        if (!firstStep) {
            console.warn("No first step available for replay.");
            return;
        }
        onRetry(entry.seed, firstStep);
    }, [onRetry]);

    const handleReplay = useCallback((entry: PlayHistory) => {
        onReplay(entry.seed, entry.actions);
    }, [onReplay]);

    const createHandleItemClick = useCallback((idx: number) => {
        return () => handleItemClick(idx);
    }, [handleItemClick]);

    const createHandleRetry = useCallback((entry: PlayHistory) => {
        return () => handleRetry(entry);
    }, [handleRetry]);

    const createHandleReplay = useCallback((entry: PlayHistory) => {
        return () => handleReplay(entry);
    }, [handleReplay]);

    return (
        <ul className="space-y-1 overflow-y-auto rounded h-full scrollbar-hide">
            {playHistory === null && (
                <li className="flex items-center justify-center h-full">
                    <div className="text-center">
                        <div className="text-4xl mb-2">⏳</div>
                        <p className="text-gray-500 dark:text-gray-400 text-sm">Loading...</p>
                    </div>
                </li>
            )}
            {playHistory?.length === 0 && (
                <li className="flex items-center justify-center h-full">
                    <div className="text-center p-8">
                        <div className="text-6xl mb-4 opacity-20">🎮</div>
                        <p className="text-gray-600 dark:text-gray-400 font-medium mb-2">No games played yet</p>
                        <p className="text-gray-400 dark:text-gray-500 text-sm">Start a new game to see your history here</p>
                    </div>
                </li>
            )}
            {playHistory?.map((entry, idx) => (
                <li
                    key={idx}
                    className="border border-transparent hover:border-gray-300 dark:hover:border-gray-600 rounded transition-all"
                >
                    <div
                        onClick={createHandleItemClick(idx)}
                        className="grid grid-cols-[max-content_max-content_1fr] gap-2 text-sm items-center text-gray-900 dark:text-gray-100 p-2 cursor-pointer"
                    >
                        <span
                            className={`font-semibold min-w-[4ch] ${entry.result === "Win"
                                ? "text-green-600 dark:text-green-400"
                                : "text-red-600 dark:text-red-400"
                                }`}
                            title={entry.result}
                        >
                            {entry.result}
                        </span>
                        <span className="text-right break-words">
                            {entry.time}s {entry.date && <span className="text-gray-500 dark:text-gray-400">({entry.date})</span>}
                        </span>
                    </div>
                    {expandedIndex === idx && (
                        <div className="p-2 pt-0">
                            <div className="text-xs text-gray-600 dark:text-gray-400 mb-2 text-center">
                                Seed: {entry.seed || 'N/A'}
                            </div>
                            <div className="flex gap-2 justify-center">
                                <button
                                    className="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                                    title="Retry game"
                                    onClick={createHandleRetry(entry)}
                                >
                                    🔄
                                </button>
                                <button
                                    className="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                                    title="Replay your actions"
                                    onClick={createHandleReplay(entry)}
                                >
                                    ▶️
                                </button>
                                {/* <button
                                    className="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                                    title="AI play"
                                    disabled
                                >
                                    🤖
                                </button> */}
                            </div>
                        </div>
                    )}
                </li>
            ))}
        </ul>
    );
});

export default PlayHistoryList;

// packages/minesweeper/src/components/sidebar/PlayHistoryList.svelte
<script lang="ts">
    import type { PlayHistory, Position, UserActionDetail } from "@caiji-games/minesweeper-core";

    let {
        playHistory,
        onRetry,
        onReplay,
    }: {
        playHistory: PlayHistory[];
        onRetry: (seed: string, firstStep: Position) => void;
        onReplay: (seed: string, actions: UserActionDetail[]) => void;
    } = $props();

    let expandedIndex = $state<number | null>(0);

    function toggle(idx: number) {
        expandedIndex = expandedIndex === idx ? null : idx;
    }

    function retry(entry: PlayHistory) {
        const firstStep = entry.actions.at(0)?.position;
        if (!firstStep) {
            console.warn("No first step available for retry.");
            return;
        }
        onRetry(entry.seed, firstStep);
    }

    function replay(entry: PlayHistory) {
        onReplay(entry.seed, entry.actions);
    }
</script>

<ul class="space-y-1 overflow-y-auto rounded h-full scrollbar-hide">
    {#if playHistory.length === 0}
        <li class="flex items-center justify-center h-full">
            <div class="text-center p-8">
                <div class="text-6xl mb-4 opacity-20">🎮</div>
                <p class="text-gray-600 dark:text-gray-400 font-medium mb-2">No games played yet</p>
                <p class="text-gray-400 dark:text-gray-500 text-sm">Start a new game to see your history here</p>
            </div>
        </li>
    {:else}
        {#each playHistory as entry, idx (idx)}
            <li class="border border-transparent hover:border-gray-300 dark:hover:border-gray-600 rounded transition-all">
                <!-- svelte-ignore a11y_click_events_have_key_events -->
                <!-- svelte-ignore a11y_no_static_element_interactions -->
                <div
                    onclick={() => toggle(idx)}
                    class="grid grid-cols-[max-content_max-content_1fr] gap-2 text-sm items-center text-gray-900 dark:text-gray-100 p-2 cursor-pointer"
                >
                    <span
                        class="font-semibold min-w-[4ch] {entry.result === 'Win' ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}"
                        title={entry.result}
                    >
                        {entry.result}
                    </span>
                    <span class="text-right break-words font-mono">
                        {entry.time}s
                        {#if entry.date}<span class="text-gray-500 dark:text-gray-400">({entry.date})</span>{/if}
                    </span>
                </div>
                {#if expandedIndex === idx}
                    <div class="p-2 pt-0">
                        <div class="text-xs text-gray-600 dark:text-gray-400 mb-2 text-center">
                            Seed: {entry.seed || "N/A"}
                        </div>
                        <div class="flex gap-2 justify-center">
                            <button
                                type="button"
                                class="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                                title="Retry game"
                                onclick={() => retry(entry)}
                            >🔄</button>
                            <button
                                type="button"
                                class="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
                                title="Replay your actions"
                                onclick={() => replay(entry)}
                            >▶️</button>
                        </div>
                    </div>
                {/if}
            </li>
        {/each}
    {/if}
</ul>
