// packages/minesweeper/src/components/board/Board.svelte
<script lang="ts">
    import { GameStatus, type Position } from "@caiji-games/minesweeper-core";
    import Cell from "./Cell.svelte";
    import type { GameState } from "../../state/game.svelte";
    import type { DesktopMouseState } from "../../state/desktopMouse.svelte";
    import type { MobileTouchState } from "../../state/mobileTouch.svelte";

    let {
        game,
        mouse,
        touch,
        highlightedCell,
    }: {
        game: GameState;
        mouse: DesktopMouseState;
        touch: MobileTouchState;
        highlightedCell?: Position;
    } = $props();

    function canPress(r: number, c: number): boolean {
        const cell = game.board[r][c];
        return (
            !cell.isRevealed &&
            !cell.isFlagged &&
            game.gameStatus !== GameStatus.GameOver &&
            game.gameStatus !== GameStatus.Win
        );
    }
</script>

<div
    class="grid"
    style:grid-template-rows="repeat({game.board.length}, 2rem)"
    style:grid-template-columns="repeat({game.board[0].length}, 2rem)"
    style:gap="2px"
    onmouseleave={mouse.onLeave}
    ontouchmove={touch.onTouchMove}
    ontouchcancel={touch.onTouchCancel}
    role="grid"
    tabindex="-1"
>
    {#each game.board as row, r (r)}
        {#each row as cell, c (c)}
            <Cell
                {cell}
                {r}
                {c}
                gameStatus={game.gameStatus}
                isPressed={mouse.isPressed(r, c, canPress(r, c))}
                isHighlighted={highlightedCell?.r === r && highlightedCell?.c === c}
                lastStepOnMine={game.revealedMinePos?.r === r && game.revealedMinePos?.c === c}
                onMouseDown={mouse.onMouseDown}
                onMouseUp={mouse.onMouseUp}
                onTouchStart={touch.onTouchStart}
                onTouchEnd={touch.onTouchEnd}
            />
        {/each}
    {/each}
</div>

// src/app/Board.tsx
import React, { useCallback, useMemo } from "react";
import Cell from "./Cell";
import { CellType } from "./Cell";
import { GameStatus, Position, UserAction } from "./Game.types";
import { useDesktopMouse } from "./hooks/useDesktopMouse";

type BoardProps = {
    board: CellType[][];
    gameStatus: GameStatus;
    highlightedCell?: Position;
    lastStepOnMine?: Position;
    rows: number;
    cols: number;
    onCellAction: (action: UserAction) => void;
};
const Board = React.memo(function Board({
    board,
    gameStatus,
    highlightedCell,
    rows,
    cols,
    lastStepOnMine,
    onCellAction,
}: BoardProps) {
    const {
        mouseAction,
        resetMouseAction,
        handleMouseDown,
        handleMouseUp,
    } = useDesktopMouse({
        gameStatus,
        onCellAction
    });
    const onLeaveBoard = useCallback(() => {
        if (gameStatus === GameStatus.GameOver || gameStatus === GameStatus.Win) return;
        if (mouseAction.leftDown || mouseAction.rightDown)
            resetMouseAction();
    }, [gameStatus, resetMouseAction, mouseAction]);
    const onMouseUpOnBoard = useCallback(() => {
        if (gameStatus === GameStatus.GameOver || gameStatus === GameStatus.Win) return;
        resetMouseAction();
    }, [gameStatus, resetMouseAction]);
    const cells = useMemo(() => {
        return board.map((row, r) => {
            return row.map((cell, c) => {
                const canPress =
                    !cell.isRevealed &&
                    !cell.isFlagged &&
                    gameStatus !== GameStatus.GameOver &&
                    gameStatus !== GameStatus.Win;
                const isPressed =
                    canPress &&
                    mouseAction.leftDown &&
                    mouseAction.position.r === r &&
                    mouseAction.position.c === c;
                const isNeighborPressed =
                    canPress &&
                    mouseAction.leftDown &&
                    Math.abs(mouseAction.position.r - r) <= 1 &&
                    Math.abs(mouseAction.position.c - c) <= 1 &&
                    mouseAction.rightDown;
                const showAsPressed = isPressed || isNeighborPressed;
                const isHighlighted = highlightedCell && highlightedCell.r === r && highlightedCell.c === c;

                return (
                    <Cell
                        key={`${r}-${c}`}
                        cell={cell}
                        r={r}
                        c={c}
                        gameStatus={gameStatus}
                        isPressed={showAsPressed ?? false}
                        isHighlighted={!!isHighlighted}
                        lastStepOnMine={lastStepOnMine?.r === r && lastStepOnMine?.c === c}
                        onMouseDown={handleMouseDown}
                        onMouseUp={handleMouseUp}
                    // onTouchStart={(e) => handleTouchStart?.(e, r, c)}
                    // onTouchEnd={(e) => handleTouchEnd?.(e, r, c)}
                    />
                );
            });
        });
    }, [board, gameStatus, mouseAction, highlightedCell, handleMouseDown, handleMouseUp, lastStepOnMine]);

    return (
        <div
            className="grid"
            style={{
                gridTemplateRows: `repeat(${rows}, 2rem)`,
                gridTemplateColumns: `repeat(${cols}, 2rem)`,
                gap: "2px",
            }}
            onMouseLeave={onLeaveBoard}
            onMouseUp={onMouseUpOnBoard}
        >
            {cells}
        </div>
    );
});

export default Board;
