// packages/sliding-puzzle/src/App.svelte
<script lang="ts">
    import { DarkModeToggle } from "@caiji-games/shared-ui";
    import SlidingPuzzle from "./components/SlidingPuzzle.svelte";
    import type { GameMode } from "./types/game";

    let mode = $state<GameMode>("number");
</script>

<div class="antialiased bg-white dark:bg-gray-900 min-h-dvh">
    <DarkModeToggle />
    <SlidingPuzzle mode={mode} onModeChange={(m) => (mode = m)} />
</div>

// packages/sliding_puzzle/src/App.tsx
import { useState } from 'react';
import SlidingPuzzle from "./components/SlidingPuzzle";
import { GameMode } from './types/game';
import { DarkModeToggle } from '@caiji-games/shared-ui';

function App() {
  const [mode, setMode] = useState<GameMode>('number');

  return (
    <div className="antialiased bg-white dark:bg-gray-900">
      <DarkModeToggle />
      <SlidingPuzzle mode={mode} onModeChange={setMode} />
    </div>
  );
}

export default App;
