// packages/sliding_puzzle/src/components/SlidingPuzzle.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { GameState, GameMode, GameStats } from '../types/game';
import { GameEngine } from '../utils/gameEngine';
import { getDefaultImageUrl } from '../utils/defaultImages';
import GameBoard from './GameBoard';
import GameStatsDisplay from './GameStatsDisplay';
import GameControl from './GameControl';

interface SlidingPuzzleProps {
  mode: GameMode;
  onModeChange: (mode: GameMode) => void;
}

const SlidingPuzzle: React.FC<SlidingPuzzleProps> = ({ mode, onModeChange }) => {
  const initState = useMemo(() => {
    const board = GameEngine.createSolvedBoard(3);
    return {
      board,
      size: 3,
      emptyIndex: board.indexOf(null),
      moves: 0,
      startTime: null,
      endTime: null,
      isCompleted: true,
    };
  }, []); 
  const [gameState, setGameState] = useState<GameState>(initState);

  const [currentTime, setCurrentTime] = useState<number>(0);
  const [selectedImage, setSelectedImage] = useState<string>(getDefaultImageUrl('simple'));
  const [showNumbers, setShowNumbers] = useState<boolean>(false);

  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;

    if (gameState.startTime && !gameState.isCompleted) {
      interval = setInterval(() => {
        setCurrentTime((t) => t + 1000);
      }, 1000);
    }

    return () => {
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [gameState.startTime, gameState.isCompleted]);

  const handleTileClick = useCallback((index: number) => {
    setGameState(prevState => {
      if (prevState.isCompleted) return prevState;

      return GameEngine.moveTile(prevState, index);
    });
  }, []);

  const handleRestart = useCallback(() => {
    const board = GameEngine.createBoard(gameState.size);
    setGameState({
      board,
      size: gameState.size,
      emptyIndex: board.indexOf(null),
      moves: 0,
      startTime: Date.now(),
      endTime: null,
      isCompleted: false,
    });
    setCurrentTime(0);
  }, [gameState.size]);

  // 开始新游戏（从统计面板触发）
  const handleNewGame = useCallback(() => {
    handleRestart();
  }, [handleRestart]);

  const handleResetGame = useCallback(() => {
    if (gameState.isCompleted) return;
    
    const solvedBoard = GameEngine.createSolvedBoard(gameState.size);
    setGameState(prevState => ({
      ...prevState,
      moves: 0,
      startTime: null,
      endTime: null,
      board: solvedBoard,
      emptyIndex: solvedBoard.indexOf(null),
      isCompleted: true,
      // 保持开始时间和移动次数不变
    }));
    setCurrentTime(0);
  }, [gameState.size, gameState.isCompleted]);

  // 改变游戏大小
  const handleSizeChange = useCallback((size: number) => {
    const board = GameEngine.createSolvedBoard(size);
    setGameState({
      board,
      size,
      emptyIndex: board.indexOf(null),
      moves: 0,
      startTime: null,
      endTime: null,
      isCompleted: true,
    });
    setCurrentTime(0);
  }, []);

  // 处理模式切换
  const handleModeChange = useCallback((newMode: GameMode) => {
    onModeChange(newMode);
    
    // 切换模式时重置游戏
    const board = GameEngine.createSolvedBoard(gameState.size);
    setGameState({
      board,
      size: gameState.size,
      emptyIndex: board.indexOf(null),
      moves: 0,
      startTime: null,
      endTime: null,
      isCompleted: true,
    });
    setCurrentTime(0);
  }, [onModeChange, gameState.size]);

  // 处理图片上传
  const handleImageUpload = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        if (e.target?.result) {
          setSelectedImage(e.target.result as string);
        }
      };
      reader.readAsDataURL(file);
    }
  }, []);

  const gameStats: GameStats = {
    moves: gameState.moves,
    time: gameState.isCompleted ?
      (gameState.endTime! - gameState.startTime!) :
      (gameState.startTime ? currentTime : 0),
    isCompleted: gameState.isCompleted,
  };

  return (
    <div className="p-4 max-w-[1200px] mx-auto min-h-screen">
      <div className="flex justify-center items-center flex-wrap gap-4">
        <h1 className="flex justify-center text-center m-1.5 text-2xl font-bold text-gray-900 dark:text-gray-100">滑动拼图</h1>
      </div>

      <div className="flex justify-center">
        <div className="flex gap-2 items-center flex-col">
          <GameControl 
            mode={mode} 
            onModeChange={handleModeChange}
            gameSize={gameState.size}
            onGameSizeChange={handleSizeChange}
            selectedImage={selectedImage}
            onImageChange={setSelectedImage}
            onImageUpload={handleImageUpload}
            showNumbers={showNumbers}
            onShowNumbersChange={setShowNumbers}
          />
          <GameStatsDisplay 
            stats={gameStats} 
            onNewGame={handleNewGame}
            onResetGame={handleResetGame}
          />
          <GameBoard
            gameState={gameState}
            mode={mode}
            selectedImage={selectedImage}
            showNumbers={showNumbers}
            onTileClick={handleTileClick}
          />
        </div>
      </div>
    </div>
  );
};

export default SlidingPuzzle;

// packages/sliding-puzzle/src/components/SlidingPuzzle.svelte
<script lang="ts">
    import type { GameMode, GameState, GameStats } from "../types/game";
    import { GameEngine } from "../utils/gameEngine";
    import { getDefaultImageUrl } from "../utils/defaultImages";
    import GameBoard from "./GameBoard.svelte";
    import GameStatsDisplay from "./GameStatsDisplay.svelte";
    import GameControl from "./GameControl.svelte";

    let {
        mode,
        onModeChange,
    }: {
        mode: GameMode;
        onModeChange: (m: GameMode) => void;
    } = $props();

    function solvedState(size: number): GameState {
        const board = GameEngine.createSolvedBoard(size);
        return {
            board,
            size,
            emptyIndex: board.indexOf(null),
            moves: 0,
            startTime: null,
            endTime: null,
            isCompleted: true,
        };
    }

    let gameState = $state<GameState>(solvedState(3));
    let currentTime = $state(0);
    let selectedImage = $state<string>(getDefaultImageUrl("simple"));
    let showNumbers = $state(false);

    let intervalId: ReturnType<typeof setInterval> | null = null;
    $effect(() => {
        if (gameState.startTime && !gameState.isCompleted) {
            intervalId = setInterval(() => {
                currentTime += 1000;
            }, 1000);
            return () => {
                if (intervalId) clearInterval(intervalId);
                intervalId = null;
            };
        }
    });

    function handleTileClick(index: number) {
        if (gameState.isCompleted) return;
        gameState = GameEngine.moveTile(gameState, index);
    }

    function startNewGame() {
        const board = GameEngine.createBoard(gameState.size);
        gameState = {
            board,
            size: gameState.size,
            emptyIndex: board.indexOf(null),
            moves: 0,
            startTime: Date.now(),
            endTime: null,
            isCompleted: false,
        };
        currentTime = 0;
    }

    function resetGame() {
        if (gameState.isCompleted) return;
        gameState = solvedState(gameState.size);
        currentTime = 0;
    }

    function changeSize(size: number) {
        gameState = solvedState(size);
        currentTime = 0;
    }

    function changeMode(newMode: GameMode) {
        onModeChange(newMode);
        gameState = solvedState(gameState.size);
        currentTime = 0;
    }

    function uploadImage(event: Event) {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (e) => {
            if (e.target?.result) selectedImage = e.target.result as string;
        };
        reader.readAsDataURL(file);
    }

    let stats = $derived<GameStats>({
        moves: gameState.moves,
        time: gameState.isCompleted
            ? gameState.endTime && gameState.startTime
                ? gameState.endTime - gameState.startTime
                : 0
            : gameState.startTime
              ? currentTime
              : 0,
        isCompleted: gameState.isCompleted,
    });
</script>

<div class="p-4 max-w-[1200px] mx-auto min-h-dvh">
    <div class="flex justify-center items-center flex-wrap gap-4">
        <h1 class="flex justify-center text-center m-1.5 text-2xl font-bold text-gray-900 dark:text-gray-100">
            滑动拼图
        </h1>
    </div>

    <div class="flex justify-center">
        <div class="flex gap-2 items-center flex-col">
            <GameControl
                {mode}
                onModeChange={changeMode}
                gameSize={gameState.size}
                onGameSizeChange={changeSize}
                {selectedImage}
                onImageChange={(img) => (selectedImage = img)}
                onImageUpload={uploadImage}
                {showNumbers}
                onShowNumbersChange={(v) => (showNumbers = v)}
            />
            <GameStatsDisplay {stats} onNewGame={startNewGame} onResetGame={resetGame} />
            <GameBoard
                {gameState}
                {mode}
                {selectedImage}
                {showNumbers}
                onTileClick={handleTileClick}
            />
        </div>
    </div>
</div>
